"""
FROZEN CONTRACT — do not edit this file. See /docs/CONTRACTS.md for the
full explanation. These are the shapes every domain agrees to produce or
consume. Import from here; never redefine these shapes locally.
"""
from pydantic import BaseModel
from typing import Optional, Literal


class CommunicationProfile(BaseModel):
    primary_language: str
    secondary_language: Optional[str] = None
    preferred_therapy_language: str
    reading_ability: Literal["pre-reader", "developing", "fluent"]
    typing_ability: Literal["none", "developing", "fluent"]
    preferred_communication_method: Literal["voice", "text", "images"]
    guardian_assistance_required: bool
    comfort_with_unfamiliar_people: Literal["low", "medium", "high"]


class CurrentUser(BaseModel):
    id: str
    role: Literal["patient", "guardian", "therapist", "supervisor"]
    name: str
    age: Optional[int] = None
    communication_profile: Optional[CommunicationProfile] = None


class ScreeningResult(BaseModel):
    case_id: str
    speech_rate: float
    pause_frequency: float
    pronunciation_score: float
    fluency_score: float
    voice_stability: float
    clarity_score: float
    confidence_level: float
    flagged_errors: list[str]  # e.g. ["s - end of words", "th - start of words"]
    plain_language_summary: str


class Milestone(BaseModel):
    id: str
    path_id: str
    order_index: int
    title: str
    goal: str
    status: Literal["locked", "active", "trained", "generalized"]
    linked_demo_id: Optional[str] = None


class ProbeResult(BaseModel):
    case_id: str
    phoneme: str
    probe_word: str
    passed: bool
    scored_at: str


class GeneralizationScore(BaseModel):
    case_id: str
    phoneme: str
    probes_attempted: int
    probes_passed: int
    rate: float


class SessionRecord(BaseModel):
    session_id: str
    case_id: str
    therapist_id: str
    activities_completed: list[str]
    homework_assigned: list[str]
    clinical_observations: str


class ModuleLibraryEntry(BaseModel):
    id: str
    phoneme: str
    age_band: str
    language: str
    title: str
    duration_seconds: int
    narration_audio_url: Optional[str] = None
    approved: bool
