export {
  SPEECH_ASSETS,
  MouthNeutral,
  MouthOpenWide,
  MouthSpread,
  MouthRounded,
  MouthBilabialClosed,
  TongueNeutral,
  TongueAlveolarTouch,
  TongueAlveolarGroove,
  TongueInterdental,
  TongueRetroflexCurl,
  TongueVelarBack,
  AirCentralStream,
  AirFrictionBurst,
  AirSoftContinuous,
  AirPlosiveRelease,
  VocalVibrationGlow,
  PalateTeethUpperLower,
} from "./SpeechAnatomyAssets";