/**
 * FROZEN CONTRACT — see /docs/CONTRACTS.md. Do not edit this file.
 * Import these shapes wherever you need them; never redeclare them
 * locally inside your own feature folder.
 */

export interface CommunicationProfile {
  primaryLanguage: string;
  secondaryLanguage?: string;
  preferredTherapyLanguage: string;
  readingAbility: "pre-reader" | "developing" | "fluent";
  typingAbility: "none" | "developing" | "fluent";
  preferredCommunicationMethod: "voice" | "text" | "images";
  guardianAssistanceRequired: boolean;
  comfortWithUnfamiliarPeople: "low" | "medium" | "high";
}

export interface CurrentUser {
  id: string;
  role: "patient" | "guardian" | "therapist" | "supervisor";
  name: string;
  age?: number;
  communicationProfile?: CommunicationProfile;
}

export interface ScreeningResult {
  caseId: string;
  speechRate: number;
  pauseFrequency: number;
  pronunciationScore: number;
  fluencyScore: number;
  voiceStability: number;
  clarityScore: number;
  confidenceLevel: number;
  flaggedErrors: string[];
  plainLanguageSummary: string;
}

export interface Milestone {
  id: string;
  pathId: string;
  orderIndex: number;
  title: string;
  goal: string;
  status: "locked" | "active" | "trained" | "generalized";
  linkedDemoId?: string;
}

export interface ProbeResult {
  caseId: string;
  phoneme: string;
  probeWord: string;
  passed: boolean;
  scoredAt: string;
}

export interface GeneralizationScore {
  caseId: string;
  phoneme: string;
  probesAttempted: number;
  probesPassed: number;
  rate: number;
}

export interface SessionRecord {
  sessionId: string;
  caseId: string;
  therapistId: string;
  activitiesCompleted: string[];
  homeworkAssigned: string[];
  clinicalObservations: string;
}

export interface ModuleLibraryEntry {
  id: string;
  phoneme: string;
  ageBand: string;
  language: string;
  title: string;
  durationSeconds: number;
  narrationAudioUrl?: string;
  approved: boolean;
}
